---
title: "Gasto I + D por Empresas en Chile"
subtitle: "Organización Industrial"
author: "Tomás Bustamante Hernández"
date: "Invierno 2022"
output: 
  beamer_presentation:
     theme: "Singapore"
     colortheme: "default"
     fonttheme: "default"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r , echo=FALSE, message=FALSE, warning=FALSE}
# descripción de variables
library(tidyverse)
library(readxl)

desc.variables<-read_xlsx("2019-I-mas-D-descriptor-de-variables.xlsx")
imasd<-read_xlsx("2019-I-mas-D-base-de-datos_sector-economico.xlsx")

```


## Evolución del gasto I+D respecto al PIB


```{r, echo=FALSE, message=FALSE, warning=FALSE}

id.pib<-read_xlsx("idpib.xlsx", sheet = 1)

pib.total<- read_xlsx("idpib.xlsx", sheet = 2, col_types = "text")

pib.total<-pib.total[1,] %>% 
  gather(key = "...1", value = "Gasto Total" )

pib.total$`Gasto Total`<- as.numeric(pib.total$`Gasto Total`)

colnames(pib.total)[1]<- "anio"

colnames(id.pib)<- c("anio", "porcentaje")


id.respecto.pib<-left_join(id.pib, pib.total, "anio")

id.respecto.pib<-id.respecto.pib %>% 
  mutate(gastoID = porcentaje*`Gasto Total`)

colnames(id.respecto.pib)[3]<-"gasto.total"

```


```{r}

ggplot(id.respecto.pib,aes(x = anio, group=1))+
  geom_line(aes(y= gasto.total/100, group=1, colour="PIB Total"), size=1)+
  geom_line(aes(y=gastoID,colour = "Gasto I + D" ), size=1)+ 
  scale_color_manual("", 
                     breaks = c("PIB Total", "Gasto I + D"),
                     values = c("red", "blue"))+
  scale_y_continuous(sec.axis = sec_axis(trans =~.*100,name = "PIB Total", labels = function(x) format(x, scientific = F)), labels = function(x) format(x, scientific = F))+
  labs(x = "Año",y = "Gasto en I + D", title = "Gasto I + D respecto al PIB", caption = "Elaboración con datos del Banco Central y Min. Ciencia")+
  theme_minimal()


```



# 

```{r}


area<- imasd %>% 
  group_by(factor(B2027, levels = c(1,2,3,4,5,6,7), labels = c("Cs Naturales", "Ingenieria y Tecnología", "Cs Medicas y Salud", "Cs Agricolas y Veterinarias", "Cs Sociales", "Humanidades y Arte", "Otra")),UNIDAD_DECLARANTE) %>% 
  summarise(Total = sum(C3020, na.rm = T))



options(scipen = 999999)

ggplot(area, aes(`factor(...)`, Total, fill = as.factor(UNIDAD_DECLARANTE)))+
  geom_col()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

view(imasd)


```

#
```{r}
empresas_imasd <- imasd %>% 
  filter(UNIDAD_DECLARANTE == 4) %>%
  group_by(ImasD,A1019) %>% 
  summarise(F.Ext = sum(C3107, na.rm = T), F.Nac = sum(C3100, na.rm = T)) %>% 
  filter(ImasD == 1)
  
total = empresas_imasd$total
empresas_imasd$total = total$F.Ext  
empresas_imasd

imasd_plot<-pivot_longer(empresas_imasd, c(F.Nac, F.Ext))

imasd_plot


ggplot(imasd_plot, aes(as.factor(A1019), value, fill = name))+
  geom_col(position = "fill")




```

```{r}



```

3100 3107